# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  nerdFontsVersion: "3"
  showIcons: true
  showFileTree: true
  mouseEvents: true
  theme:
    activeBorderColor:
      - "#89ddff"
      - bold
    inactiveViewSelectedLineBgColor:
      - "#2c2f3d"
    inactiveBorderColor:
      - "#2c2f3d"
    optionsTextColor:
      - "#3d59a1"
    selectedLineBgColor:
      - "#292e42"
      - bold
  commitLength:
    show: true

  spinner:
    # The frames of the spinner animation.
    frames:
      - "⣷ "
      - "⣯ "
      - "⣟ "
      - "⡿ "
      - "⢿ "
      - "⣻ "
      - "⣽ "
      - "⣾ "
    rate: 100
