"$schema" = 'https://starship.rs/config-schema.json'

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"

[package]
disabled = true
